# Generated by Django 5.0.4 on 2024-09-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_profile_address_remove_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
