# Generated by Django 5.0.4 on 2024-09-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_remove_bill_user_remove_budget_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
