# Generated by Django 5.0.4 on 2024-09-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
